name: ToDoApp

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - run: cp -r /web/actions-runner/_work/todo-project/todo-project/build/ /web/todoapp/
